{
 "title": "бизнес-транзакции General (UC)3",
 "tags": [ "general" ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Time",
    "query": "1s, 30s,1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   { "name": "data_source", "query": "influxdb" },
   {
    "name": "application",
    "query": "SHOW TAG VALUES WITH KEY = \"application\" "
   },
   {
    "name": "script_name",
    "query": "SHOW TAG VALUES WITH KEY = \"transaction\" WHERE \"transaction\" =~ /^UC\\d{2}.*$/"
   },
   {
    "name": "all_script_names",
    "query": "SHOW TAG VALUES WITH KEY = \"transaction\" WHERE \"transaction\" =~ /^UC\\d{2}.*$/"
   },
   {
    "name": "node_name",
    "query": "SHOW TAG VALUES WITH KEY = \"application\" "
   }
  ]
 },
 "panels": [
  { "title": "after test statistics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "response time $script_name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "response time, sec" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT \"avg\"/1000 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /$application/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^$script_name.*$/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/ksed/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$script_name.*$/" }
     ]
    }
   ]
  },
  {
   "title": "errors count $script_name",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "short", "label": "errors count per min" }
   ],
   "targets": [
    {
     "alias": "$tag_transaction",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /$application/ AND \"statut\" = 'ko' AND \"transaction\" =~ /^$script_name.*$/) AND $timeFilter GROUP BY time(1m), \"transaction\" fill(null)",
     "select": [
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "count"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/ksed|cauk/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/^$script_name_old.*$/" }
     ]
    }
   ]
  },
  {
   "title": "Transaction's stats for table full",
   "type": "table",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") as \"summary\" FROM  \"autogen\".\"jmeter\" WHERE (\"application\" =~ /$application/ AND \"statut\" = 'all' AND \"transaction\" =~ /^UC\\d{2}.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") as \"passed\" FROM  \"autogen\".\"jmeter\" WHERE (\"application\" =~ /$application/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^UC\\d{2}.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    },
    {
     "groupBy": [
      { "params": [ "$Time" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") as \"failed\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /$application/ AND \"statut\" = 'ko' AND \"transaction\" =~ /^UC\\d{2}.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "pct95.0" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/ksed/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/tr_TK/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$Time" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT (min(\"min\")+1)/1000 as \"min\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /$application/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^UC\\d{2}.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "pct95.0" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/ksed/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/tr_TK/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$Time" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT max(\"max\")/1000 as \"max\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /$application/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^UC\\d{2}.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "pct95.0" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/ksed/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/tr_TK/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$Time" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT median(\"avg\")/1000 as \"median\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /$application/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^UC\\d{2}.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "pct95.0" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/ksed/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/tr_TK/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$Time" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"avg\")/1000 as \"avg\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /$application/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^UC\\d{2}.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "pct95.0" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/ksed/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/tr_TK/" }
     ]
    },
    {
     "groupBy": [
      { "params": [ "$Time" ], "type": "time" },
      { "params": [ "transaction" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"pct90.0\")/1000 as \"percentile 90\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /$application/ AND \"statut\" = 'ok' AND \"transaction\" =~ /^UC\\d{2}.*/) AND $timeFilter GROUP BY \"transaction\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ],
      [
       { "params": [ "avg" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ],
      [
       { "params": [ "pct95.0" ], "type": "field" },
       { "params": [ "95" ], "type": "percentile" }
      ],
      [
       { "params": [ "min" ], "type": "field" },
       {
        "params": [],
        "type": "min"
       }
      ],
      [
       { "params": [ "max" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ],
      [
       { "params": [ "countError" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/ksed/" },
      { "condition": "AND", "key": "transaction", "operator": "=~", "value": "/tr_TK/" }
     ]
    }
   ]
  },
  {
   "title": "errors info",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "groupBy": [
      { "params": [ "responseCode" ], "type": "tag" },
      { "params": [ "responseMessage" ], "type": "tag" },
      { "params": [ "transaction" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") AS \"errors summary\" FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /$application/ AND \"responseCode\" != '0' AND \"responseCode\" != '') AND $timeFilter GROUP BY \"responseCode\", \"responseMessage\", \"transaction\", \"application\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/ksed|cauk|mk/" },
      { "condition": "AND", "key": "responseCode", "operator": "=~", "value": "/0/" }
     ]
    }
   ]
  },
  {
   "title": "transactions summary - current info",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 }
  },
  {
   "title": "all transactions summary",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "All transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") AS \"all\" FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" =~ /UC/ AND \"application\" =~ /$application/ AND  \"statut\" = 'all') AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "passed transactions summary",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Error transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") as \"error\" FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" =~ /UC/ AND \"statut\" = 'ok' AND \"application\" =~ /$application/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "failed transactions summary",
   "type": "stat",
   "gridPos": { "h": 3, "w": 4, "x": 8, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "alias": "Error transaction",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") as \"error\" FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" =~ /UC/ AND \"statut\" = 'ko' AND \"application\" =~ /$application/) AND $timeFilter",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "scripts threads count",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 6, "x": 12, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "distinctCount" ] } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"maxAT\") FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" = 'internal' AND \"application\" =~ /$application/) AND $timeFilter Group By \"application\"\n",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/UC/" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/ksed/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    }
   ]
  },
  {
   "title": "scripts fails count",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 6, "x": 18, "y": 30 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "application" ], "type": "tag" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" =~ /^UC$all_script_names.*$/ AND \"application\" =~ /$application/ AND \"statut\" = 'ko') AND $timeFilter GROUP BY \"application\"",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/^UC$all_script_names.*$/" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/ksed/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ko" }
     ]
    }
   ]
  },
  {
   "title": "transactions passed/failed",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short", "label": "transactions per minute" }
   ],
   "targets": [
    {
     "alias": "passes",
     "groupBy": [
      { "params": [ "10m" ], "type": "time" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"count\") FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" =~ /UC/ AND \"application\" =~ /$application/ AND \"statut\" = 'ok') AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=~", "value": "/UC/" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/ksed/" },
      { "condition": "AND", "key": "statut", "operator": "=", "value": "ok" }
     ]
    },
    {
     "alias": "fails",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT sum(\"count\") FROM \"jmeter\" WHERE (\"application\" =~ /$application/ AND \"statut\" = 'ko' AND \"transaction\" =~ /UC/) AND $timeFilter GROUP BY time(1m)",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "title": "threads and throughput", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 43 } },
  {
   "title": "active threads summary",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 44 },
   "yaxes": [
    { "format": "short", "label": "threads per minute" }
   ],
   "targets": [
    {
     "alias": "threads",
     "groupBy": [
      { "params": [ "$Time" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT sum(\"threads_per_script\") FROM (SELECT last(\"maxAT\") AS \"threads_per_script\" FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" = 'internal' AND \"application\" =~ /$application/) AND $timeFilter GROUP BY \"application\", time($Time)) GROUP BY time($Time)",
     "select": [
      [
       { "params": [ "maxAT" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "internal" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/ksed|cauk|mk/" }
     ]
    }
   ]
  },
  {
   "title": "throughput",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 44 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "alias": "summary",
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT mean(\"count\")/5 FROM \"autogen\".\"jmeter\" WHERE (\"application\" =~ /$application/ AND \"transaction\" =~ /^UC\\d{2}.*/ AND \"statut\" = 'ok' ) AND $timeFilter GROUP BY time(1m) fill(null)",
     "select": [
      [
       { "params": [ "count" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "application", "operator": "=~", "value": "/ksed/" },
      { "condition": "AND", "key": "transaction", "operator": "!~", "value": "/UC/" },
      { "condition": "AND", "key": "responseCode", "operator": "!=", "value": "0" }
     ]
    }
   ]
  },
  {
   "title": "active threads per node-$node_name",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 54 },
   "yaxes": [
    { "format": "short", "label": "threads per minute" }
   ],
   "targets": [
    {
     "alias": "$tag_application",
     "groupBy": [
      { "params": [ "$Time" ], "type": "time" },
      { "params": [ "application" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "jmeter",
     "query": "SELECT last(\"maxAT\") FROM \"autogen\".\"jmeter\" WHERE (\"transaction\" = 'internal' AND \"application\" =~ /^$application.*$node_name$/) AND $timeFilter GROUP BY time($Time), \"application\" fill(null)",
     "select": [
      [
       { "params": [ "maxAT" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       }
      ]
     ],
     "tags": [
      { "key": "transaction", "operator": "=", "value": "internal" },
      { "condition": "AND", "key": "application", "operator": "=~", "value": "/ksed|cauk|mk/" }
     ]
    }
   ]
  }
 ]
}